# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import json, subprocess
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:.\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x920")
window.configure(bg="#050A24")

canvas = Canvas(
    window,
    bg="#050A24",
    height=920,
    width=1200,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    600.0,
    463.0,
    image=image_image_1
)

canvas.create_text(
    266.0,
    124.0,
    anchor="nw",
    text="Qcm Desktop Application",
    fill="#FFFFFF",
    font=("MontserratAlternates Bold", 48 * -1)
)

canvas.create_rectangle(
    278.0,
    269.0,
    922.0,
    780.0,
    fill="#FFFFFF",
    outline=""
)

canvas.create_text(
    506.0,
    287.0,
    anchor="nw",
    text="Welcome Back",
    fill="#000000",
    font=("MontserratAlternates Regular", 24 * -1)
)

canvas.create_text(
    401.0,
    402.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("MontserratAlternates Regular", 24 * -1)
)

canvas.create_text(
    401.0,
    513.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("MontserratAlternates Regular", 24 * -1)
)

canvas.create_text(
    312.0,
    332.0,
    anchor="nw",
    text="Login To Your Account",
    fill="#000000",
    font=("MontserratAlternates Bold", 48 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    603.0,
    575.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    show="*"  # Masquer le mot de passe
)
entry_1.place(
    x=410.0,
    y=552.0,
    width=386.0,
    height=44.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    603.0,
    463.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=410.0,
    y=440.0,
    width=386.0,
    height=44.0
)

try:
    with open("Login.json", 'r') as file:
        data = json.load(file)
except (FileNotFoundError, json.JSONDecodeError):
    data = {"users": []}


def login(name: str, password: str):
    if not name or not password:
        messagebox.showwarning("Warning", "Please fill in all fields.")
        return
    for user in data["users"]:
        if name.lower() == user["name"].lower() and password == user["password"]:
            messagebox.showinfo("Login Successful", f"Welcome back, {name}! \nNow, continue  the main application in the interface console :) ")
            return user
    messagebox.showerror("Login Failed", "Invalid username or password!")


def open_registration_form():
    # Close the login window
    window.destroy()
    # Open the registration form file
    subprocess.Popen(["python3", "C:.\gui\gui2\gui.py"])


button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login(entry_2.get().strip(), entry_1.get().strip()),
    relief="flat"
)

button_1.place(
    x=493.0 + 130,
    y=631.0,
    width=213.0,
    height=75.0
)
button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_registration_form,
    relief="flat"
)
button_5.place(
    x=350.0,
    y=631.0,
    width=213.0,
    height=75.0
)
window.bind("<Return>", lambda event: login(entry_2.get().strip(), entry_1.get().strip()))

button_image_hover_1 = PhotoImage(
    file=relative_to_assets("button_hover_1.png"))


def button_1_hover(e):
    button_1.config(
        image=button_image_hover_1
    )


def button_1_leave(e):
    button_1.config(
        image=button_image_1
    )


button_1.bind('<Enter>', button_1_hover)
button_1.bind('<Leave>', button_1_leave)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    151.0,
    158.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
